### ISSUE TITLE
From frontend-meet: Changes to the mono-repo

### ISSUE THREAD

**Issue by AskeLange** [limbo-works/limbo-frontend#20]
Present changes to the mono-repo, and related.

## Todo:

- [ ] Remove `nuxt-link-ext` from wip-packages. 
- [ ] Remove the `screens` package pull-request and issue.
- [ ] Write about JSDocs in documentation and link to the docs.
- [ ] Correct naming, especially in JS-packages, but do also use `dev` instead of serve.
- [ ] Add package-issues for `CookieInformationBlocker` and `UmbracoSvg`.
- [ ] See if we can dual-publish to yarn.

## Updated Lerna

Updated Lerna to version [5.5.0](https://github.com/lerna/lerna/releases/tag/v5.5.0) from version [4.0.0](https://github.com/lerna/lerna/releases/tag/v4.0.0).

The only relevant breaking changes were that node v12 and previous were no longer supported. Fortunately we were already using `lts/fermium` (v14), so this shouldn't provide any issues. Our continuous integration workflow were using node v12 however, so this have been updated to reflect the version in the `.nvmrc` file. I've only been able to do surface-level testing without republishing a package, so if you run into any issues, feel free to poke at me.  

## Changes to Husky

Added `yarn test` to pre-commit husky check, just to make sure nothing is broken when committing. 

## Added issues for packages

See GitHub project: [here](https://github.com/orgs/limbo-works/projects/20/views/1).
Also added issue templates to the [limbo-frontend repository](https://github.com/limbo-works/limbo-frontend).

Added the following:

### Components

- [x] Accordion.
- [x] AutoComplete (missing description).
- [x] Dropdown.
- [x] LimboSearch.
- [x] LongRead (missing description).
- [ ] SkipToContent.
- [x] SwiperWrap. 
- [x] VideoPlayer (missing description).
- [x] AxiosForm.
- [x] CookieInformation (missing description).
- [ ] CookieInformationBlocker (should be added).
- [ ] HeadingX.
- [x] LinkTile.
- [x] NuxtLinkExt.
- [x] PostScribeScript.
- [x] StructuredData (missing description).
- [x] TransitionExt.
- [x] UmbracoForm (missing description).
- [ ] UmbracoSvg (should be added).

### Directives

- [ ] Tab directive (should perhaps be added, at some point).
- [ ] Trap focus directive  (should perhaps be added, at some point).

## Wrote documentation

See documentation [here](https://github.com/limbo-works/limbo-frontend).

### `.npmrc`

Request GitHub PAT, and adds a new .npmrc file, which is required to, among other things, publish packages.

### `package`

Requests type (vue or javascript), name and description, which is used to generate a new package.
Currently the JS-type package consists of an `index.js` file and a `dev` directory.
Currently the Vue-type package consists of `src`, `dev` and  `test` directories. 
The naming sort of gives their purpose away.

**Discuss:**
- [ ] Should we have the possibility to add TypeScript packages - or just be really good at writing JSDocs comments, which there's actually a plugin for? (see [here](https://marketplace.visualstudio.com/items?itemName=stevencl.addDocComments)). Write something about the documentation - link to docs.
- [ ] There's some general naming issues with JavaScript packages, fx. everything dev-related is called `serve` - taking directly from the Vue-packages - this should probably not be the case.

## Other

There's currently five unresolved tasks in the mono-repo README, what's the status on these? 
There's currently an unresolved pull-request from Saul for the `screens` package. Should this be merged?

In the pull-request described above, Fjordside also asks whether or not freelancers will be able to install packages.
The answer to which is yes, given that the packages aren't private. If they are, they might need to be added as collaborators.
